### ISSUE TITLE
404 when running npm start

### ISSUE THREAD

**Issue by SenecaX** [gmolveau/electron-express-angular#1]
Hello, I'm trying to use your boilerplate but when doing "npm start", i'm getting 404 not found and don't know where to look. Can you please help?

**Comment by gmolveau** [comment]
Hi, I pushed a commit (4a0986f7705b43ceef0b6015ef6e702063e2c947), it should now work. Apparently angular changed the way it builds and now creates another subfolder.

**Comment by gmolveau** [comment]
4a0986f7705b43ceef0b6015ef6e702063e2c947
